# Site settings
title: ItalAI
email: italailabs@gmail.com
description: Italian excellence in artificial intelligence
baseurl: "/index/" # the subpath of your site, e.g. /blog/
url: "italailabs.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: ItalAILabs

# Build settings
markdown: kramdown
